### ISSUE TITLE
Notify 消息通知组件使用提示Notify is not defined

### ISSUE THREAD

**Issue by ZdMirLong** [jwaterwater/uni-nutui#10]
如题 ,在 uni-app中使用Notify 消息通知组件,点击按钮提示 Notify is not defined
```html
                 <view>
			<nut-cell is-Link @click="baseNotify('基础用法')">消息通知基础用法</nut-cell>
		</view>


	/**
			 * 消息通知 
			 */
			baseNotify(msg) {
				Notify.text(msg, {
					onClose: () => {
						console.log('close');
					},
					onClick: () => {
						console.log('click');
					}
				});
			}
```

报错信息如下:
```text
vue.runtime.esm.js:1400 
        
       Uncaught ReferenceError: Notify is not defined
    at Proxy.baseNotify (index.vue:369:5)
    at _createVNode.onClick._cache.<computed>._cache.<computed> (index.vue:138:30)
    at callWithErrorHandling (vue.runtime.esm.js:1336:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1345:21)
    at emit$1 (vue.runtime.esm.js:1902:9)
    at vue.runtime.esm.js:8780:53
    at handleClick (index.vue:49:7)
    at callWithErrorHandling (vue.runtime.esm.js:1336:22)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1345:21)
    at HTMLElement.invoker (vue.runtime.esm.js:9676:9)
```

**Comment by jwaterwater** [comment]
参考demo的写法, uni环境不能写dom, 只能组件形式调用
